### ISSUE TITLE
Running tests on CI

### ISSUE THREAD

**Issue by hvelarde** [tallus/python-civicrm#12]
if you explain me how you run tests, I can set up a Travis CI configuration so the code is tested on every commit.

you will also need to enable the Travis CI webhook on the repo configuration.

**Comment by eracle** [comment]
Hello there! 
In order to properly test an api client, I usually see two possible ways:
- mocking the expected responses (from the requests library);
- running a dockerized civcrm web server where to launch the tests;

Regards!

**Comment by hvelarde** [comment]
thanks, I'm no longer working on this.

**Comment by eracle** [comment]
Thanks. I've forked and added CI and Tox.
https://github.com/eracle/civicrm_api_client

I will work on this, in order to fix it, in the future.
