### ISSUE TITLE
Mock a CiviCRM server

### ISSUE THREAD

**Issue by hvelarde** [tallus/python-civicrm#15]
to test my code, I'm trying to mock a CiviCRM server using [httmock](https://github.com/patrys/httmock).

I'm copying the return data from a testing CiviCRM server and I found an issue while using ``get`` ``GroupContact``: the result of the call is a dictionary of dictionaries instead of a list of dictionaries:

```python
(Pdb) groups
{u'1': {u'group_id': u'2', u'title': u'Newsletter Subscribers', u'visibility': u'Public Pages', u'in_method': u'Email', u'is_hidden': u'0', u'in_date': u'2013-02-25 09:10:15', u'id': u'1'}, u'76': {u'group_id': u'4', u'title': u'Advisory Board', u'visibility': u'Public Pages', u'in_method': u'Email', u'is_hidden': u'0', u'in_date': u'2013-07-14 08:48:57', u'id': u'76'}}
```

the source code is here: https://github.com/collective/collective.civicrm/blob/master/src/collective/civicrm/browser/contact.py#L55

I was checking your code and I saw you're testing against a live server and I was wondering if you are interested in implementing some mocking to be able to test the code better.

what I have done until now is here: https://github.com/collective/collective.civicrm/commit/1188b96412e2840ace655c5bf73c3c9e7f7d402b

**Comment by tallus** [comment]
https://github.com/tallus/python-civicrm/pull/18 added basic unit tests
